### ISSUE TITLE
Not repairing certain items with B:Restricted=false

### ISSUE THREAD

**Issue by Thiana** [smbarbour/Reconstructor#3] opened 2015-02-21 13:13 UTC
Reconstructor 2.0a is not repairing certain items even when B:Restricted=false.

Examples:
- Dark Iron Armor (EnderIO)
- Diamond Dolly (Jabba)
- Chisel (Chisel2)
- Tinker Tools (Tinker's Construct) -- Though I suspect this is deliberate?

Thanks.

**Comment by smbarbour** [comment] 2015-02-21 17:56
The Reconstructor only works when the items take simple damage and are marked as repairable.  Dark Iron Armor can be empowered which results in non-simple damage.  The dolly is specifially non-repairable. I'm not sure about the chisel.  The Tinker's tools have a variety of upgrades that affect how repairing is done.

Other things that don't repair in a Reconstructor that I know of are IC2 unpowered tools and FMP saws.  I'm sure there are other things as well.

**Closed by smbarbour** 2015-02-21 17:56 UTC
Labels: wontfix

**Comment by smbarbour** [comment] 2015-06-22 16:58
For Chisel2, I found the cause of this in the Chisel2 code and supplied the appropriate fix to the devs (as well as adding the ability for the chisels to be repaired on an anvil as well)
